name: Go Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # 添加触发标签发布的支持
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        goos: [linux]  # 支持不同操作系统
        goarch: [amd64, arm64]  # 支持不同架构

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 使用最新版的 checkout

      - name: Set up Go
        uses: actions/setup-go@v3  # 设置 Go 版本
        with:
          go-version: '1.20'

      - name: Cache Go modules
        uses: actions/cache@v3  # 使用缓存加速依赖管理
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build with Go
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -trimpath -buildmode=pie -o dist/Client-${{ matrix.goarch }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # 使用最新版的上传构建产物
        with:
          name: Client-${{ matrix.goarch }}
          path: dist/Client-${{ matrix.goarch }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 使用最新版的 checkout

      - name: Install GitHub CLI
        run: |
          # 安装 GitHub CLI（gh）
          sudo apt-get install gh

      - name: Create a new Git tag
        run: |
          # 获取最新的标签版本
          VERSION=$(git describe --tags --abbrev=0)
          if [ -z "$VERSION" ]; then
            VERSION="v1.0.0"  # 默认标签版本
          fi
          echo "Creating tag: v${VERSION}"
          git tag -a v${VERSION} -m "Release v${VERSION}"  # 创建标签
          git push origin v${VERSION}  # 推送标签

      - name: Create a Release
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          gh release create v${VERSION} dist/* --title "Release v${VERSION}" --notes "Release v${VERSION}"